### PR TITLE
Implement block memory allocator

### PR DESCRIPTION
**Pull request by antoinealb**
First real code for libcanard :)

I implemented the memory block allocator, or at least how I think it should behave. This is my first try at doing that kind of things so let me know if anything is wrong.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Great start, Antoine. :)

I didn't actually ran the code, so my input is based solely on eyeing the sources.

## API functions

The design document explicitly lists the functions that shall be exposed to the library's user. We can go back and review them if necessary, although I don't think it is necessary - the defined function set covers all features of the library.

The problem I identified with this PR is that it exposes functions and data structures that are *internal* to the library through the library's header (namely, `CanardPoolAllocatorBlock`, `CanardPoolAllocator`, `canardInitPoolAllocator`, `canardAllocateBlock`, `canardFreeBlock`). They are supposed to be hidden, so as to not pollute the API.

On the other hand, if the internals are completely hidden from the user, the unit tests will have to gain access to them using some other ways. I can propose two solutions off the top of my head:

- Include `canard.c` as a header into every source file with unit tests. There should be nothing wrong with this approach, although I realize that it's a bit unusual.
- Create a second header file for library-internal definitions, like `canard_internal.h`, and put all of the internal type and macro definitions there. Define a macro for use instead of `static` for internal functions, say `CANARD_INTERNAL`, and set it to `static` for release builds, and empty value for testing builds.

I prefer the first solution because it's much simpler and much less intrusive.

## Coding style

A few corrections:

- Braces go on the new line.
- Pointer star goes to the type name, not to the identifier: `int* foo`.
- We have agreed to use C99, which means that we can write cleaner code: variables can be defined in the place of first use and declared `const` ([example of the problem](https://github.com/UAVCAN/libcanard/pull/1/files#diff-ec9999a8cb27a176bf926dd68dfd7426R17)); we can use `//` comments instead of strictly `/* */`.

Declaring variables in the beginning of the block is generally a bad idea, because such style is prone to using variables uninitialized. There's [a section dedicated to this problem in the style guide](https://github.com/Zubax/zubax_style_guide#variables) (MISRA goes into further detail here).

**Comment by antoinealb** [comment]
I am against including `canard.c`, because it will require linker-tweaking to avoid multiple definitions of the same symbol (one per inclusion). It could also hide problems such as missing headers in `canard.c` (if they are included in the test file before it). I prefer the `canard_internals.h` approach.

I will do the changes you suggest regarding style.

**Comment by antoinealb** [comment]
PR updated with your suggestions.

**Comment by pavel-kirienko** [comment]
Nice.

Next time I'd suggest to either configure your IDE to handle formatting automatically (here's config for Eclipse: <ftp://pkir.net/zubax_style_formatter.xml>), or use [uncrustify as described here](https://github.com/Zubax/zubax_style_guide#autoformatting). Currently there are still some inconsistencies in pointer stars and brace placement.

As for API - in order to enforce internal linkage, `static` must be placed in front of both *definition* and *declaration*, unless declaration comes after. So internal functions in canard.c should also be prepended with `CANARD_INTERNAL`.

**Comment by antoinealb** [comment]
Oh nice did not know about uncrustify, applied it :+1: 

Also added `static` qualifier to declarations.

**Pull request merged**
