### PR TITLE
Create Android.bp

### PR DESCRIPTION
**Pull request by manmountain**
Build libcanard for Android Open Source Project

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Thanks! I have two questions:

1. Can you please describe in a few sentences the intended use case for this, perhaps in the header comment of the file you just added? Otherwise, somebody not familiar with Android native (like myself) might get lost.

2. Can you set up a basic CI pipeline for this in `.travis.yml`?

**Comment by pavel-kirienko** [comment]
Or maybe it's better to extract this build recipe into a separate platform-specific component?

**Comment by pavel-kirienko** [comment]
> Or maybe it's better to extract this build recipe into a separate platform-specific component?

To be more specific, I suggest we create `/android/libcanard` and put all Android-specific items in there.

**Comment by manmountain** [comment]
Do you mean to create `/android/libcanard` in `platform_specific_components`? And put libcanard's Android.bp file in that repo also?

**Comment by pavel-kirienko** [comment]
> Do you mean to create /android/libcanard in platform_specific_components? And put libcanard's Android.bp file in that repo also?

Yes to both.

**Comment by manmountain** [comment]
The best thing for now is maybe just to merge the Android.bp make files to a 'android' branch in both libcanard and platform_specific_components repos. Im working on adding a /android/libcanard that using the hardware abstraction layer for the can bus on Android platforms to platform_specific_components.

**Comment by pavel-kirienko** [comment]
> The best thing for now is maybe just to merge the Android.bp make files to a 'android' branch in both libcanard and platform_specific_components repos.

Why is that better though? Does your workflow depend on that branch being available? I'm not sure I understand the motivation here.

I can help you set up the platform-specific repo for Android if you want, although I can't think of anything requiring setting up beyond creating the directory and adding a new build pipeline to travis.yml.

**Comment by pavel-kirienko** [comment]
@manmountain are you planning to update this PR?

**Comment by pavel-kirienko** [comment]
Closing as stale. Feel free to re-open if you get back to this later.

**Pull request closed without merging**
